#!/usr/bin/env node
// PROTOTYPE — throwaway (wayfinder ticket #30).
// Generates src/components/prototype/content.ts FROM the canonical .astro
// components. Mechanical extraction — no hand transcription (verbatim rule).

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const comp = (f) => readFileSync(join(root, 'src/components', f), 'utf8');

const clean = (s) =>
  s.replace(/<[^>]+>/g, '')     // strip any residual tags
   .replace(/\s+/g, ' ')
   .trim();

/** Parse <p>-block prayer components: segments split by <br />, each
 *  optionally led by <strong>Guía:</strong> or <strong>Todos:</strong>. */
function parseDialogComponent(file) {
  const src = comp(file);
  const heading = clean(src.match(/<h2>([\s\S]*?)<\/h2>/)[1]);
  const blocks = [...src.matchAll(/<p>([\s\S]*?)<\/p>/g)].map((m) => {
    const lines = m[1].split(/<br\s*\/?\s*>/).map((seg) => {
      let who = undefined;
      let text = seg;
      const lead = seg.match(/^\s*<strong>\s*(Guía|Todos)\s*:\s*<\/strong>/);
      if (lead) { who = lead[1]; text = seg.slice(lead[0].length); }
      return { ...(who ? { who } : {}), text: clean(text) };
    }).filter((l) => l.text.length > 0);
    return { lines };
  });
  return { heading, blocks };
}

/** Parse Letanías: <li> invocation <br /> <strong>response</strong></li> */
function parseLetanias() {
  const src = comp('Letanias.astro');
  const heading = clean(src.match(/<h2>([\s\S]*?)<\/h2>/)[1]);
  const items = [...src.matchAll(/<li>([\s\S]*?)<\/li>/g)].map((m) => {
    const [call, resp] = m[1].split(/<br\s*\/?\s*>/);
    return { call: clean(call), response: clean(resp) };
  });
  return { heading, items };
}

/** Parse Misterios.tsx data: label / days / items per set. */
function parseMisterios() {
  const src = readFileSync(join(root, 'src/components/Misterios.tsx'), 'utf8');
  const sets = [];
  const setRe = /'([a-z]+)':\s*\{\s*label:\s*'([^']+)',\s*days:\s*\[([^\]]*)\],\s*items:\s*\[([\s\S]*?)\]\s*\}/g;
  for (const m of src.matchAll(setRe)) {
    sets.push({
      key: m[1],
      label: m[2],
      days: [...m[3].matchAll(/'([^']+)'/g)].map((d) => d[1]),
      items: [...m[4].matchAll(/^\s*'([^']+)'\S*,?\s*$/gm)].map((i) => i[1]),
    });
  }
  return sets;
}

const section = (id, src) => ({ id, heading: src.heading, blocks: src.blocks });

const data = {
  sections: [
    section('oracion-inicial', parseDialogComponent('OracionInicial.astro')),
    { id: 'misterios', heading: 'Lectura de los Misterios', misterios: parseMisterios() },
    section('intenciones-santo-padre', parseDialogComponent('OracionIntencionesSantoPadre.astro')),
    section('jaculatorias', parseDialogComponent('Jaculatorias.astro')),
    { id: 'letanias', ...parseLetanias() },
    section('oracion-final', parseDialogComponent('OracionFinal.astro')),
  ],
};

const banner = `/* eslint-disable */
// PROTOTYPE — throwaway (wayfinder ticket #30). GENERATED by
// scripts/prototype/generate-content.mjs from the canonical .astro texts.
// Prayer texts are verbatim — do not hand-edit (map hard rule).

export interface Line { who?: string; text: string }
export interface Block { lines: readonly Line[] }
export interface DialogSection { id: string; heading: string; blocks: readonly Block[] }
export interface MisterioSet { key: string; label: string; days: readonly string[]; items: readonly string[] }
export interface MisteriosSection { id: 'misterios'; heading: string; misterios: readonly MisterioSet[] }
export interface LitaniaItem { call: string; response: string }
export interface LetaniasSection { id: 'letanias'; heading: string; items: readonly LitaniaItem[] }
export type Section = DialogSection | MisteriosSection | LetaniasSection;
export interface PrayerData { sections: readonly Section[] }
`;

const out = `${banner}
export const PRAYER: PrayerData = ${JSON.stringify(data, null, 2)};
`;
const dest = join(root, 'src/components/prototype/content.ts');
writeFileSync(dest, out);
console.log(`wrote ${dest}: ${data.sections.length} sections, ` +
  `${data.sections.reduce((n, s) => n + (s.items?.length ?? 0), 0)} letanía invocations`);
