/* eslint-disable */
// PROTOTYPE — throwaway (wayfinder ticket #30). GENERATED by
// scripts/prototype/generate-content.mjs from the canonical .astro texts.
// Prayer texts are verbatim — do not hand-edit (map hard rule).

export interface Line { who?: string; text: string }
export interface Block { lines: readonly Line[] }
export interface DialogSection { id: string; heading: string; blocks: readonly Block[] }
export interface MisterioSet { key: string; label: string; days: readonly string[]; items: readonly string[] }
export interface MisteriosSection { id: 'misterios'; heading: string; misterios: readonly MisterioSet[] }
export interface LitaniaItem { call: string; response: string }
export interface LetaniasSection { id: 'letanias'; heading: string; items: readonly LitaniaItem[] }
export type Section = DialogSection | MisteriosSection | LetaniasSection;
export interface PrayerData { sections: readonly Section[] }

export const PRAYER: PrayerData = {
  "sections": [
    {
      "id": "oracion-inicial",
      "heading": "Oración Inicial",
      "blocks": [
        {
          "lines": [
            {
              "who": "Guía",
              "text": "Por la Señal de la Santa Cruz, de nuestros enemigos libranos Señor, Dios nuestro. En el nombre del Padre, del Hijo y del Espíritu Santo."
            },
            {
              "who": "Todos",
              "text": "Amén."
            }
          ]
        },
        {
          "lines": [
            {
              "who": "Todos",
              "text": "Señor mío Jesucristo, Dios y Hombre verdadero, creador y redentor mío, por ser tú quien eres y porque te amo sobre todas las cosas, me pesa de todo corazón haberte ofendido. Propongo firmemente enmendarme, confesarme y cumplir la penitencia que me fuese impuesta, ofrezco mi vida, obras y trabajos en satisfacción de mis pecados."
            },
            {
              "text": "Confío en tu bondad y misericordia infinita que me perdonarás por tu preciosa sangre, y me darás la gracia para nunca más pecar."
            },
            {
              "text": "Amén."
            }
          ]
        }
      ]
    },
    {
      "id": "misterios",
      "heading": "Lectura de los Misterios",
      "misterios": [
        {
          "key": "gozosos",
          "label": "Misterios Gozosos (Lunes y Sábado)",
          "days": [
            "Monday",
            "Saturday"
          ],
          "items": [
            "El anuncio del Ángel a María.",
            "La visita de la Santísima Virgen a Santa Isabel.",
            "El nacimiento de Jesús en el portal de Belén.",
            "La presentación de Jesús en el templo.",
            "Jesús perdido y hallado en el templo."
          ]
        },
        {
          "key": "luminosos",
          "label": "Misterios Luminosos (Jueves)",
          "days": [
            "Thursday"
          ],
          "items": [
            "El Bautismo de Cristo en el Jordán.",
            "Su auto revelación en las bodas de Caná.",
            "El anuncio del Reino y llamado a la conversión.",
            "La Transfiguración del Señor.",
            "La Institución de la Eucaristía."
          ]
        },
        {
          "key": "dolorosos",
          "label": "Misterios Dolorosos (Martes y Viernes)",
          "days": [
            "Tuesday",
            "Friday"
          ],
          "items": [
            "La oración de Jesús en el Huerto.",
            "La flagelación de Jesús.",
            "Jesús es coronado de espinas.",
            "Jesús con la Cruz a cuestas.",
            "La crucifixión y muerte de Jesús."
          ]
        },
        {
          "key": "gloriosos",
          "label": "Misterios Gloriosos (Miércoles y Domingo)",
          "days": [
            "Wednesday",
            "Sunday"
          ],
          "items": [
            "La Resurrección de Nuestro Señor Jesucristo.",
            "La Ascensión de Jesús al Cielo.",
            "La venida del Espíritu Santo.",
            "La asunción de María al Cielo.",
            "La coronación y glorificación de María."
          ]
        }
      ]
    },
    {
      "id": "intenciones-santo-padre",
      "heading": "Oración por las intenciones del Santo Padre",
      "blocks": [
        {
          "lines": [
            {
              "who": "Guía",
              "text": "Padre nuestro, que estas en cielo, santificado sea tu Nombre; venga a nosotros tu reino; hágase tu voluntad en la tierra como en el cielo..."
            },
            {
              "who": "Todos",
              "text": "Danos hoy nuestro pan de cada día, perdona nuestras ofensas, como también nosotros perdonamos a los que nos ofenden, no nos dejes caer en la tentación y líbranos del mal."
            }
          ]
        },
        {
          "lines": [
            {
              "who": "Guía",
              "text": "Alegrate María, llena eres de gracia, el Señor está contigo, bendita eres entre las mujeres y bendito es el fruto de tu vientre, Jesús..."
            },
            {
              "who": "Todos",
              "text": "Santa María Madre de Dios, ruega por nosotros los pecadores, ahora y en la hora de nuestra muerte. Amén."
            }
          ]
        },
        {
          "lines": [
            {
              "who": "Guía",
              "text": "Gloria al Padre, al Hijo y al Espíritu Santo..."
            },
            {
              "who": "Todos",
              "text": "Como era en el principio, ahora y siempre, por los siglos de los siglos. Amén."
            }
          ]
        }
      ]
    },
    {
      "id": "jaculatorias",
      "heading": "Jaculatorias",
      "blocks": [
        {
          "lines": [
            {
              "who": "Guía",
              "text": "Oh Soberano Santuario, Sagrario del Verbo Eterno..."
            },
            {
              "who": "Todos",
              "text": "Libra, Virgen, del infierno a los que rezan tu Rosario."
            }
          ]
        },
        {
          "lines": [
            {
              "who": "Guía",
              "text": "Emperatriz poderosa de los mortales consuelo..."
            },
            {
              "who": "Todos",
              "text": "Ábrenos, Virgen el cielo con una muerte dichosa."
            }
          ]
        },
        {
          "lines": [
            {
              "who": "Guía",
              "text": "Padre nuestro, que estas en cielo, santificado sea tu Nombre; venga a nosotros tu reino; hágase tu voluntad en la tierra como en el cielo..."
            },
            {
              "who": "Todos",
              "text": "Danos hoy nuestro pan de cada día, perdona nuestras ofensas, como también nosotros perdonamos a los que nos ofenden, no nos dejes caer en la tentación y líbranos del mal."
            }
          ]
        },
        {
          "lines": [
            {
              "who": "Guía",
              "text": "Dios te salve, María Santísima, hija de Dios Padre, Virgen Purísima y castísima antes del parto, en tus manos encomiendo toda mi fe para que la alumbres, llena eres de gracia, el Señor está contigo, bendita eres entre las mujeres y bendito es el fruto de tu vientre, Jesús..."
            },
            {
              "who": "Todos",
              "text": "Santa María Madre de Dios, ruega por nosotros los pecadores, ahora y en la hora de nuestra muerte. Amén."
            }
          ]
        },
        {
          "lines": [
            {
              "who": "Guía",
              "text": "Dios te salve, María Santísima, madre de Dios Hijo, Virgen Purísima y castísima en el parto, en tus manos encomiendo mi esperanza para que la alientes, llena eres de gracia, el Señor está contigo, bendita eres entre las mujeres y bendito es el fruto de tu vientre, Jesús..."
            },
            {
              "who": "Todos",
              "text": "Santa María Madre de Dios, ruega por nosotros los pecadores, ahora y en la hora de nuestra muerte. Amén."
            }
          ]
        },
        {
          "lines": [
            {
              "who": "Guía",
              "text": "Dios te salve, María Santísima, esposa de Dios Espíritu Santo, Virgen Purísima y castísima después del parto, en tus manos encomiendo mi caridad para que la inflames, llena eres de gracia, el Señor está contigo, bendita eres entre las mujeres y bendito es el fruto de tu vientre, Jesús..."
            },
            {
              "who": "Todos",
              "text": "Santa María Madre de Dios, ruega por nosotros los pecadores, ahora y en la hora de nuestra muerte. Amén."
            }
          ]
        },
        {
          "lines": [
            {
              "who": "Guía",
              "text": "Dios te salve, María Santísima, templo, trono y sagrario de la Santísima Trinidad, Virgen concebida sin culpa original, Dios te salve..."
            },
            {
              "who": "Todos",
              "text": "Reina y Madre, Madre de misericordia, vida, dulzura y esperanza nuestra: Dios te salve; a ti llamamos los desterrados hijos de Eva; a ti suspiramos gimiendo y llorando en este valle de lágrimas. ¡Ea!, Pues, Señora, abogada nuestra, vuelve a nosotros esos tus ojos misericordiosos y después, de este destierro muéstranos a Jesús fruto bendito de tu vientre, ¡Oh clemente! ¡Oh piadosa! ¡Oh dulce Virgen María!."
            }
          ]
        },
        {
          "lines": [
            {
              "who": "Guía",
              "text": "Ruega por nosotros, Santa, Madre de Dios, para que seamos dignos de alcanzar las divinas gracias y promesas de nuestro señor Jesucristo, Amén."
            }
          ]
        }
      ]
    },
    {
      "id": "letanias",
      "heading": "Letanías",
      "items": [
        {
          "call": "Señor, ten piedad de nosotros.",
          "response": "Señor, ten piedad de nosotros."
        },
        {
          "call": "Cristo, ten piedad de nosotros.",
          "response": "Cristo, ten piedad de nosotros."
        },
        {
          "call": "Señor, ten piedad de nosotros.",
          "response": "Señor, ten piedad de nosotros."
        },
        {
          "call": "Cristo, óyenos.",
          "response": "Cristo, óyenos."
        },
        {
          "call": "Cristo, escúchanos.",
          "response": "Cristo, escúchanos."
        },
        {
          "call": "Dios Padre celestial.",
          "response": "Ten piedad de nosotros."
        },
        {
          "call": "Dios Hijo Redentor del mundo.",
          "response": "Ten piedad de nosotros."
        },
        {
          "call": "Dios Espíritu Santo.",
          "response": "Ten piedad de nosotros."
        },
        {
          "call": "Santísima Trinidad que eres un solo Dios.",
          "response": "Ten piedad de nosotros."
        },
        {
          "call": "Santa María.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Santa Madre de Dios.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Santa Virgen de las vírgenes.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Madre de Jesucristo.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Madre de la Iglesia.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Madre de la divina Gracia.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Madre Purísima.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Madre Castísima.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Madre Virgen.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Madre Inmaculada.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Madre Amable.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Madre Admirable.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Madre del buen Consejo.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Madre del Creador.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Madre del Salvador.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Virgen Prudentísima.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Virgen Venerable.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Virgen Clemente.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Virgen Poderosa.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Virgen Fiel.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Espejo de Justicia.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Trono de Sabiduría.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Causa de nuestra Alegría.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Vaso Espiritual.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Vaso Honorable.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Vaso insigne de Devoción.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Rosa Mística.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Torre de David.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Casa de Oro.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Arca de la Alianza.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Puerta del Cielo.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Estrella de la Mañana.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Salud de los enfermos.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Consolador de los Afligidos.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Refugio de los pecadores.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Auxilio de los cristianos.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Reina de los Ángeles.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Reina de los Patriarcas.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Reina de los Profetas.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Reina de los Apóstoles.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Reina de los Mártires.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Reina de los Confesores.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Reina de las Vírgenes.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Reina de todos los Santos.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Reina concebida sin pecado original.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Reina elevada al cielo.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Reina del Santo Rosario.",
          "response": "Ruega por nosotros."
        },
        {
          "call": "Reina de la Paz.",
          "response": "Ruega por nosotros."
        }
      ]
    },
    {
      "id": "oracion-final",
      "heading": "Oración Final",
      "blocks": [
        {
          "lines": [
            {
              "who": "Guía",
              "text": "Cordero de Dios que quitas el pecado del mundo."
            },
            {
              "who": "Todos",
              "text": "Perdónanos Señor."
            }
          ]
        },
        {
          "lines": [
            {
              "who": "Guía",
              "text": "Cordero de Dios que quitas el pecado del mundo."
            },
            {
              "who": "Todos",
              "text": "Óyenos Señor."
            }
          ]
        },
        {
          "lines": [
            {
              "who": "Guía",
              "text": "Cordero de Dios que quitas el pecado del mundo."
            },
            {
              "who": "Todos",
              "text": "Ten piedad y misericordia de nosotros."
            }
          ]
        },
        {
          "lines": [
            {
              "who": "Guía",
              "text": "Bajo tu amparo nos acogemos, Santa Madre de Dios, no desprecies las súplicas que te hacemos en nuestras necesidades, antes bien, líbranos de todos los peligros, oh Virgen gloriosa y bendita. Ruega por nosotros, Santa Madre de Dios..."
            },
            {
              "who": "Todos",
              "text": "Para que seamos dignos de alcanzar las promesas de Nuestro Señor Jesucristo. Amén."
            }
          ]
        },
        {
          "lines": [
            {
              "who": "Guía",
              "text": "Oh Dios, cuyo Unigénito Hijo, con su vida, muerte y resurrección, nos alcanzó el premio de la vida eterna: concédenos, a los que recordamos estos misterios del Santo Rosario, imitar lo que contienen y alcanzar lo que prometen. Por el mismo Jesucristo, nuestro Señor."
            },
            {
              "who": "Todos",
              "text": "Amén."
            }
          ]
        }
      ]
    }
  ]
};
