name: CI/CD

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Detect Yarn Cache Directory
        id: cache-yarn
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Setup Yarn Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache-yarn.outputs.dir }}
          key: cache-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install Javascript Packages
        run: yarn install --silent --ignore-scripts --non-interactive --no-progress

      - name: Lint Project
        run: yarn lint
